---

# NB: netcat-openbsd is required if using virt-manager GUI (requires -U option).

- apt_key:
    url=http://zfsonlinux.org/4D5843EA.asc
    state=present

- apt_repository:
    repo='deb http://archive.zfsonlinux.org/debian jessie main'
    state=present
    update_cache=yes

- apt: name={{ item }} state=present install_recommends=no default_release=jessie-backports
  with_items:
    - build-essential # for zfs
    - openntpd
    - kvm
    - qemu-kvm
    - libvirt-bin
    - virtinst
    - bridge-utils
    - netcat-openbsd
    - linux-image-amd64
    - linux-headers-amd64

- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - debian-zfs

- service: name=openntpd state=started enabled=yes

# TODO:
# - had to "rm /boot/bzImage-3.14.32-xxxx-grs-ipv6-64" otherwise it would
#   boot automatically on this kernel, and this causes issues with dkms for ZFS.

# - /etc/network/interfaces configuration.

- name: Deploy the network interfaces configuration
  template:
    src: "etc/network/interfaces"
    dest: "/etc/network/interfaces"
    owner: "root"
    group: "root"
    mode: 0644

# Enable IP forwarding in /etc/sysctl.d/99-sysctl.conf by uncommenting:
# - net.ipv4.ip_forward=1
# - net.ipv6.conf.all.forwarding=1

#
# For more documentation on KVM server(s), see their host_vars file.
# Ex: host_vars/padthai.civicrm.org.
#
