---

- name: Create the curator directory in the root user directory
  file: path=/root/.curator state=directory mode=0700 owner=root group=root
  tags:
    - logstash-curator

- name: Deploy the curator configuration file
  template:
    src: "root/curator/curator.yml"
    dest: "/root/.curator/curator.yml"
    mode: 0600
  tags:
    - logstash-curator
