---

# Fix drush on Aegir and re-run the upgrade
# To use it: $ ansible-playbook ./hacks/fix_icinga2_aegir.yml 

- hosts: aegir_managed
  tasks:
    - name: Download provision_symbiotic from Github
      git: repo=https://github.com/coopsymbiotic/provision_symbiotic.git
           version=master
           dest=/var/aegir/.drush/provision_symbiotic
           update=yes
    - name: Run Verify
      shell: "drush @hm provision-verify"
  become: true
  become_user: aegir
