---

# Restart Icinga. Sometimes the satellites do not reconnect after a network outage.
# To use it: $ ansible-playbook ./hacks/restart_icinga.yml 

- hosts: icinga-nodes
  tasks:
    - shell: systemctl restart icinga2
  become: true
  become_user: root
