---

# Run Debian upgrades
# To use it: $ ansible-playbook ./helpers/upgrade_debianfix.yml

- hosts: all
  tasks:
    - shell: apt update
    - shell: yes n | dpkg --configure -a
      ignore_errors: True
    - shell: apt -f install -y
      ignore_errors: True
  become: true
  become_user: root
