---

# Run Debian upgrades
# To use it: $ ansible-playbook ./helpers/upgrade_debianfix.yml

- hosts: all
  tasks:
    - shell: apt update
      ignore_errors: True
      async: 60
      poll: 5
    - shell: yes n | apt upgrade
      ignore_errors: True
      async: 60
      poll: 5
    - shell: dpkg --configure -a
      ignore_errors: True
      async: 60
      poll: 5
    - shell: apt -f install -y
      ignore_errors: True
      async: 60
      poll: 5
    - shell: apt upgrade -y
      async: 60
      poll: 5
  become: true
  become_user: root
