---

- name: restart opendkim
  systemd:
    state: restarted
    daemon_reload: yes
    name: opendkim

- name: restart postfix
  systemd:
    state: restarted
    name: postfix

- name: postmap sasl_pass
  shell: postmap /etc/postfix/sasl/sasl_pass
  notify: restart postfix

- name: reload systemd
  systemd:
    daemon_reload: yes
