---
- apt_key:
    url=https://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state=present
  tags:
    - packages

- apt_repository:
    repo='deb http://packages.elasticsearch.org/logstashforwarder/debian stable main'
    state=present
    update_cache=yes
  tags:
    - packages

- apt: pkg=logstash-forwarder state=installed
  tags:
    - packages

- name: Deploy the logstash-forwarder configuration.
  template:
    src: "logstash-forwarder.conf"
    dest: "/etc/logstash-forwarder.conf"
    owner: "root"
    group: "root"
    mode: 0644
  notify: restart logstash-forwarder

- copy: src=/etc/ansible/files/etc/ssl/private/{{ logstash_ssl_ca_cert }} dest=/etc/ssl/private/{{ logstash_ssl_ca_cert }} owner=root group=ssl-cert mode=0640
  notify: restart logstash-forwarder
