---

# Required for Grafana
- apt: pkg=apt-transport-https state=present
  tags:
    - packages
    - grafana

- apt_key:
    url=https://packages.grafana.com/gpg.key
    state=present
  tags:
    - packages
    - grafana

# https://grafana.com/docs/grafana/latest/installation/debian/
- apt_repository:
    repo='deb https://packages.grafana.com/oss/deb stable main'
    state=present
    update_cache=yes
  tags:
    - packages
    - grafana

- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - grafana
  tags:
    - packages
    - grafana

- name: Deploy the grafana basic configuration files
  template:
    src="{{ item }}"
    dest="/{{ item }}"
    owner=root group=grafana mode=0640
  with_items:
    - etc/grafana/grafana.ini
  notify: restart grafana
  tags:
    - grafana
    - grafana-base-configs
