---
- hosts: servers
  sudo: yes
  roles:
    - common-all
    - logcheck
    - logstash-forwarder
    - sslcerts

- hosts: kvm-hosts
  sudo: yes
  roles:
    - common-kvmhosts

- hosts: aegir-managed
  sudo: yes
  roles:
    - aegir

- hosts: backup-servers
  sudo: yes
  roles:
    - backupserver

- hosts: logstash-servers
  sudo: yes
  roles:
    - logstash

- hosts: icinga-servers
  sudo: yes
  roles:
    - icinga

- hosts: redmine-servers
  sudo: yes
  roles:
    - redmine

- hosts: yubiauth-managed
  sudo: yes
  roles:
    - yubiauth

- hosts: rdiff-backups
  sudo: yes
  roles:
    - backupninja-rdiff

- hosts: civicrm-environment
  sudo: yes
  roles:
    - civicrm-environment

- hosts: openwrt-mesh-nodes
  sudo: yes
  gather_facts: no
  roles:
    - openwrt-babelmesh

- hosts: munin-nodes
  sudo: yes
  roles:
    - munin-node

- hosts: postfix-servers
  sudo: yes
  roles:
    - postfix

- hosts: dokuwiki-instances
  sudo: yes
  roles:
    - dokuwiki

- hosts: ufw-managed
  sudo: yes
  roles:
    - ufw
