---
- hosts: servers
  sudo: yes
  roles:
    - common-all
    - icinga2
    - logcheck
    - filebeat
    - backupninja-rdiff
    - mysqlbackup
    - ufw
    - unattended-upgrades
  tags:
    - base

- hosts: symbiotic-servers
  sudo: yes
  roles:
    - sshuserkeys
  tags:
    - sshuserkeys

- hosts: kvm-servers
  sudo: yes
  roles:
    - kvm-server
  tags:
    - kvm-server

- hosts: aegir-managed
  sudo: yes
  roles:
    - aegir
    - postfix
    - gitlab-runner
    - dehydrated
  tags:
    - aegir

- hosts: aegir-managed
  sudo: yes
  roles:
    - gitlab-runner
  tags:
    - gitlab-runner

- hosts: postfix-servers
  sudo: yes
  roles:
    - postfix
  tags:
    - postfix

- hosts: backup-servers
  sudo: yes
  roles:
    - backup-server
  tags:
    - backup-server

- hosts: logstash-servers
  sudo: yes
  roles:
    - logstash
  tags:
    - logstash

- hosts: loki-servers
  sudo: yes
  roles:
    - loki
  tags:
    - loki

- hosts: icinga-servers
  sudo: yes
  roles:
    - icinga2
    - grafana
    - gitlab-runner
  tags:
    - icinga
    - icinga2

- hosts: servers
  sudo: yes
  roles:
    - icinga2
  tags:
    - icinga2

- hosts: redmine-servers
  sudo: yes
  roles:
    - redmine
  tags:
    - redmine

- hosts: gitlab-servers
  sudo: yes
  roles:
    - gitlab
  tags:
    - gitlab

- hosts: php-servers
  sudo: yes
  roles:
    - php
  tags:
    - php

- hosts: buildkit-servers
  sudo: yes
  roles:
    - buildkit
  tags:
    - buildkit

- hosts: yubiauth-managed
  sudo: yes
  roles:
    - yubiauth
  tags:
    - yubiauth

- hosts: rdiff-backups
  sudo: yes
  roles:
    - backupninja-rdiff
  tags:
    - backupninja-rdiff

- hosts: munin-nodes
  sudo: yes
  roles:
    - munin-node
  tags:
    - munin-node

- hosts: dokuwiki-instances
  sudo: yes
  roles:
    - dokuwiki
  tags:
    - dokuwiki

- hosts: ufw-managed
  sudo: yes
  roles:
    - ufw
  tags:
    - ufw

# For hosts not running Aegir
# or with more custom setups
- hosts: dehydrated-manually
  sudo: yes
  roles:
    - dehydrated
  tags:
    - dehydrated

- hosts: docker-servers
  sudo: yes
  roles:
    - docker
    - gitlab-runner
  tags:
    - docker

- hosts: mattermost-servers
  sudo: yes
  roles:
    - mattermost
  tags:
    - mattermost
