---
- hosts: servers
  sudo: yes
  roles:
    - common-all
    - icinga2
    - logcheck
    - filebeat
    - backupninja-rdiff
    - ufw
    - unattended-upgrades
  tags:
    - base

- hosts: symbiotic-servers
  sudo: yes
  roles:
    - sshuserkeys
  tags:
    - sshuserkeys

- hosts: kvm-servers
  sudo: yes
  roles:
    - kvm-server
  tags:
    - kvm-server

- hosts: aegir-managed
  sudo: yes
  roles:
    - aegir
    - postfix
  tags:
    - aegir

- hosts: postfix-servers
  sudo: yes
  roles:
    - postfix
  tags:
    - postfix

- hosts: sslcerts
  sudo: yes
  roles:
    - sslcerts
  tags:
    - sslcerts
    - sslcertificates

- hosts: aegir-managed
  sudo: yes
  roles:
    - civicrm-environment
  tags:
    - civicrm-environment

- hosts: backup-servers
  sudo: yes
  roles:
    - backup-server
  tags:
    - backup-server

- hosts: logstash-servers
  sudo: yes
  roles:
    - logstash
  tags:
    - logstash

- hosts: icinga-servers
  sudo: yes
  roles:
    - icinga2
  tags:
    - icinga
    - icinga2

- hosts: servers
  sudo: yes
  roles:
    - icinga2
  tags:
    - icinga2

- hosts: redmine-servers
  sudo: yes
  roles:
    - redmine
  tags:
    - redmine

- hosts: gitlab-servers
  sudo: yes
  roles:
    - gitlab
  tags:
    - gitlab

- hosts: php70-servers
  sudo: yes
  roles:
    - php70fpm
  tags:
    - php70fpm

- hosts: yubiauth-managed
  sudo: yes
  roles:
    - yubiauth
  tags:
    - yubiauth

- hosts: rdiff-backups
  sudo: yes
  roles:
    - backupninja-rdiff
  tags:
    - backupninja-rdiff

- hosts: munin-nodes
  sudo: yes
  roles:
    - munin-node
  tags:
    - munin-node

- hosts: dokuwiki-instances
  sudo: yes
  roles:
    - dokuwiki
  tags:
    - dokuwiki

- hosts: ufw-managed
  sudo: yes
  roles:
    - ufw
  tags:
    - ufw

# For hosts not running Aegir
# or with more custom setups
- hosts: dehydrated-manually
  sudo: yes
  roles:
    - dehydrated
  tags:
    - dehydrated

- hosts: docker-servers
  sudo: yes
  roles:
    - docker
  tags:
    - docker
