---
- hosts: servers
  become: yes
  roles:
    - common-all
    - icinga2
    - filebeat
    - promtail
    - backupninja-rdiff
    - borgmatic
    - mysqlbackup
    - ufw
    - unattended-upgrades
  tags:
    - base

- hosts: symbiotic-servers
  become: yes
  roles:
    - sshuserkeys
  tags:
    - sshuserkeys

- hosts: kvm-servers
  become: yes
  roles:
    - kvm-server
  tags:
    - kvm-server

- hosts: aegir-managed
  become: yes
  roles:
    - aegir
    - postfix
    - gitlab-runner
    - dehydrated
  tags:
    - aegir

- hosts: postfix-servers
  become: yes
  roles:
    - postfix
  tags:
    - postfix

- hosts: backup-servers
  become: yes
  roles:
    - backup-server
  tags:
    - backup-server

- hosts: logstash-servers
  become: yes
  roles:
    - logstash
  tags:
    - logstash

- hosts: loki-servers
  become: yes
  roles:
    - loki
  tags:
    - loki

# NB: icinga role intentionally not added because it is already
# running for all servers, so it would make the role run twice.
- hosts: icinga-servers
  become: yes
  roles:
    - grafana
    - gitlab-runner
    - loki
  tags:
    - icinga
    - icinga2

- hosts: gitlab-servers
  become: yes
  roles:
    - gitlab
  tags:
    - gitlab

- hosts: php-servers
  become: yes
  roles:
    - php
  tags:
    - php

- hosts: buildkit-servers
  become: yes
  roles:
    - buildkit
  tags:
    - buildkit

- hosts: yubiauth-managed
  become: yes
  roles:
    - yubiauth
  tags:
    - yubiauth

- hosts: rdiff-backups
  become: yes
  roles:
    - backupninja-rdiff
  tags:
    - backupninja-rdiff

- hosts: civicrm-sites
  become: yes
  roles:
    - civicrm-sites
  tags:
    - civicrm-sites

- hosts: dokuwiki-instances
  become: yes
  roles:
    - dokuwiki
  tags:
    - dokuwiki

- hosts: ufw-managed
  become: yes
  roles:
    - ufw
  tags:
    - ufw

# For hosts not running Aegir
# or with more custom setups
- hosts: dehydrated-manually
  become: yes
  roles:
    - dehydrated
  tags:
    - dehydrated

- hosts: docker-servers
  become: yes
  roles:
    - docker
    - gitlab-runner
  tags:
    - docker

- hosts: mattermost-servers
  become: yes
  roles:
    - mattermost
  tags:
    - mattermost
