---

- name: Check if promtail needs to be installed or upgraded
  stat: path="/usr/local/bin/.promtail-{{ promtail_version }}.txt"
  register: p
  tags:
    - packages
    - packages-promtail
    - promtail

- name: Deploy the promtail binary
  get_url:
    url: "https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/promtail-linux-amd64.zip"
    dest: /usr/local/bin/promtail.zip
    mode: '0640'
  when: p.stat.exists == False
  tags:
    - packages
    - packages-promtail
    - promtail

# Consider using the unarchive module rather than running 'unzip'.
- name: Unzip the promtail binary
  shell: "unzip -u /usr/local/bin/promtail.zip && touch /usr/local/bin/.promtail-{{ promtail_version }}.txt"
  when: p.stat.exists == False
  tags:
    - packages
    - packages-promtail
    - promtail

- name: Delete the promtail gzip file
  file: path="/usr/local/bin/promtail.zip" state=absent
  tags:
    - packages
    - packages-promtail
    - promtail

- name: Promtail binary file permissions
  file: path="/usr/local/bin/promtail" owner=root group=root mode=0755
  tags:
    - packages
    - packages-promtail
    - promtail

- name: Promtail lib directory permissions
  file: path="/var/lib/promtail" state=directory owner=root group=root mode=0700
  tags:
    - promtail

- name: Promtail systemd unit file
  template: src=etc/systemd/system/promtail.service dest=/etc/systemd/system/promtail.service owner=root group=root mode=0644
  tags:
    - promtail

- name: Promtail configuration file
  template: src=etc/promtail.yaml dest=/etc/promtail.yaml owner=root group=root mode=0644
  notify: restart promtail
  tags:
    - promtail
    - promtail-config

- name: Enable the promtail service
  systemd:
    name: promtail
    enabled: yes
    masked: no
  tags:
    - promtail
