---

# Setup extra crons (see the README.md for details)

- template:
    src="etc/systemd/system/civiextracron.service"
    dest="/etc/systemd/system/civicrm_{{ item.key }}_{{ inventory_hostname_short | replace('-', '_') }}.service"
    owner=root
    group=root
    mode=0644
  with_dict: "{{ civicrm_sites_extra_crons | default({}) }}"
  notify: reload systemd

- template:
    src="etc/systemd/system/civiextracron.timer"
    dest="/etc/systemd/system/civicrm_{{ item.key }}_{{ inventory_hostname_short | replace('-', '_') }}.timer"
    owner=root
    group=root
    mode=0644
  with_dict: "{{ civicrm_sites_extra_crons | default({}) }}"
  notify: reload systemd

# Not necessary?
# - systemd:
#     name: "civicrm_{{ item.key }}_{{ inventory_hostname_short }}.service"
#     enabled: yes
#   with_dict: "{{ civicrm_sites_extra_crons | default({}) }}"

- systemd:
    name: "civicrm_{{ item.key }}_{{ inventory_hostname_short | replace('-', '_') }}.timer"
    enabled: yes
  with_dict: "{{ civicrm_sites_extra_crons | default({}) }}"
