---

- name: Drupal | Check if CiviCRM is installed (i.e. has civicrm.settings.php)
  stat:
    path: "{{ site_path }}/civicrm.settings.php"
  register: civicrm_is_active

- name: Drupal | Run civicrm database upgrades
  become_user: aegir
  shell:
    chdir: "{{ site_path }}"
    cmd: cv --no-interaction --out=json-pretty upgrade:db
  when: civicrm_is_active.stat.exists

- name: Drupal | Update logging schema as a precaution after upgrades
  become_user: aegir
  shell:
    chdir: "{{ site_path }}"
    cmd: cv api symbiotic.fixschemalog
  ignore_errors: yes

- name: Drupal | Run civicrm extension database upgrades
  become_user: aegir
  shell:
    chdir: "{{ site_path }}"
    cmd: cv api Extension.upgrade

- include_tasks: drupal-civicrm-cron.yml
  when: "'civicrm_sites' in group_names"
  tags:
    - civicrm-sites-cron-drupal
