---
- hosts: redmineservers
  sudo: yes

  # Assumes Debian Jessie with Redmine 3.0.x

  tasks:
    - name: Create the redmine user manually, since we want a home.
      user: name=redmine

    - name: Install base packages for Redmine (git, mysql-server, redmine, redmine-mysql).
      apt: update_cache=yes
      apt: pkg=git state=installed
      apt: pkg=mysql-server state=installed
      apt: pkg=nginx state=installed
      apt: pkg=redmine=2.* state=installed default_release=wheezy-backports
      apt: pkg=redmine-mysql state=installed
      apt: pkg=libmysqlclient-dev state=installed

      # imagemagick is only used to export Gantt charts to PNG.
      # can be avoided by using:
      # bundle install --without development test rmagick
      # apt: pkg=ImageMagick state=installed

    - name: Install various packages required for gem compilation (libicu-dev, zlib1g-dev).
      apt: pkg=libicu-dev state=installed
      apt: pkg=zlib1g-dev state=installed
      apt: pkg=libssl-dev state=installed

    # redmine_git_hosting needs this
    # http://redmine-git-hosting.io/get_started/#step-1-install-dependencies
    - name: Install more packages required for rugged-gitolite
      apt: pkg=pkg-config state=installed
      apt: pkg=cmake state=installed
      apt: pkg=libssh2-1 state=installed
      apt: pkg=libssh2-1-dev state=installed

    - name: Install Puma from ruby gem.
      shell: gem install puma
      args:
        creates: /usr/local/bin/puma

    # No idea why this is necessary, but some bundle complained..
    - name: Install shoulda-matchers gem
      shell: gem install shoulda-matchers -v 2.7.0

    # TODO: nginx vhost?
    # TODO: create the various directories in /home/redmine/redmine/{log,tmp}
    # TODO: create ssh key for 'redmine' user for gitolite.
    # -> place key in /usr/share/redmine/plugins/redmine_git_hosting/ssh_keys/redmine_gitolite_admin_id_rsa
    # -> chown redmine.redmine

    # TODO : create /usr/share/redmine/Gemfile.local with : gem 'puma'

    # TODO: deploy template /home/redmine/config/puma.rb
    # mkdir /usr/share/redmine/plugins

    - name: Deploy the Redmine init script (for puma).
      template:
        src: "templates/etc-init-redmine"
        dest: "/etc/init.d/redmine"
        owner: "root"
        group: "root"
        mode: 0755

    - name: Enable Redmine init script for default boot levels.
      shell: update-rc.d redmine defaults

    - name: Change permissions on various Redmine directories
      shell: dpkg-statoverride --update --force --add redmine redmine 0755 /var/cache/redmine
      shell: dpkg-statoverride --update --force --add redmine redmine 0755 /var/cache/redmine/default
      shell: dpkg-statoverride --update --force --add redmine redmine 0755 /var/cache/redmine/default/plugin_assets
      shell: dpkg-statoverride --update --force --add redmine redmine 0755 /var/cache/redmine/default/cache
      shell: chown -R redmine.redmine /var/cache/redmine
      shell: dpkg-statoverride --update --force --add redmine redmine 0750 /var/log/redmine
      shell: chown -R redmine.redmine /var/log/redmine
      shell: dpkg-statoverride --update --force --add redmine redmine 0755 /var/lib/redmine/default
      shell: dpkg-statoverride --update --force --add redmine redmine 0755 /var/lib/redmine/default/files
      shell: chown -R redmine.redmine /var/lib/redmine

    - name: Change permissions on Redmine configuration files.
      shell: dpkg-statoverride --update --force --add redmine redmine 0640 /etc/redmine/default/session.yml
      shell: dpkg-statoverride --update --force --add redmine redmine 0640 /etc/redmine/default/database.yml

    - name: Install the gitolite package (assuming that redmine and git are on the same server).
      apt: pkg=gitolite3 state=installed

    - name: Checkout plugins for redmine/git integration (redmine_bootstrap_kit, redmine_git_hosting).

      git: repo=https://github.com/jbox-web/redmine_bootstrap_kit.git
           dest=/usr/share/redmine/plugins/redmine_bootstrap_kit
           version=0.2.3
           update=yes

      # TODO: must "bundle install" this..
      git: repo=https://github.com/jbox-web/gitolite-rugged.git
           dest=/usr/share/redmine/plugins/gitolite_rugged
           update=yes

      git: repo=https://github.com/jbox-web/redmine_git_hosting.git
           dest=/usr/share/redmine/plugins/redmine_git_hosting
           version=1.1.0
           update=yes

      git: repo=https://github.com/mlutfy/redmine_stealth.git
           dest=/usr/share/redmine/plugins/redmine_stealth
           update=yes

    # "Redmine Agile" plugin and dependancies
    - name: Install Redmine Agile
      git: repo=https://github.com/RCRM/redmine_agile.git
           dest=/usr/share/redmine/plugins/redmine_agile

    - name: Redmine Agile, run bundle install
      shell: bundle install --without development test RAILS_ENV=production
      args:
        chdir: /usr/share/redmine/plugins/redmine_agile

    - name: Redmine Agile, run rake
      shell: rake redmine:plugins NAME=redmine_agile RAILS_ENV=production
      args:
        chdir: /usr/share/redmine/plugins/redmine_agile

    # TODO: ln -s /var/log/redmine /usr/share/redmine/log
    # (because git_hosting wants to log there)

    # chown redmine.redmine /usr/share/redmine/plugins/redmine_git_hosting/bin/

    - name: Deploy the Redmine configuration for smtp notifications.
      template:
        src: "templates/etc-redmine-default-configuration.yml"
        dest: "/etc/redmine/default/configuration.yml"
        owner: "redmine"
        group: "redmine"
        mode: 0644

    - name: Restart Redmine.
      service: name=redmine state=restarted
