---
- hosts: amioun.net5.bidon.ca
  sudo: yes

  tasks:
    - name: Create the redmine user manually, since we want a home.
      user: name=redmine

    - name: Make sure that wheezy-backports apt repository is available (for redmine 2.x).
      apt_repository:
        repo='deb http://ftp.ca.debian.org/debian wheezy-backports main'
        state=present
        update_cache=yes

    - name: Install base packages for Redmine (git, mysql-server, redmine, redmine-mysql).
      apt: update_cache=yes
      apt: pkg=git state=installed
      apt: pkg=mysql-server state=installed
      apt: pkg=nginx state=installed
      apt: pkg=redmine=2.* state=installed default_release=wheezy-backports
      apt: pkg=redmine-mysql state=installed

    - name: Install various packages required for gem compilation (libicu-dev, zlib1g-dev).
      apt: pkg=libicu-dev state=installed
      apt: pkg=zlib1g-dev state=installed
      apt: pkg=libssl-dev state=installed

    - name: Install Puma from ruby gem.
      shell: gem install puma
      args:
        creates: /usr/local/bin/puma

    # TODO: nginx vhost?
    # TODO: create the various directories in /home/redmine/redmine/{log,tmp}
    # TODO: create ssh key for 'redmine' user for gitolite.
    # TODO: deploy template /home/redmine/config/puma.rb

    - name: Deploy the Redmine init script (for puma).
      template:
        src: "templates/etc-init-redmine"
        dest: "/etc/init.d/redmine"
        owner: "root"
        group: "root"
        mode: 0755

    - name: Enable Redmine init script for default boot levels.
      shell: update-rc.d redmine defaults

    - name: Change permissions on various Redmine directories
      shell: dpkg-statoverride --update --force --add redmine redmine 0750 /var/cache/redmine
      shell: dpkg-statoverride --update --force --add redmine redmine 0750 /var/cache/redmine/default
      shell: dpkg-statoverride --update --force --add redmine redmine 0750 /var/cache/redmine/default/plugin_assets
      shell: dpkg-statoverride --update --force --add redmine redmine 0750 /var/cache/redmine/default/cache
      shell: chown -R redmine.redmine /var/cache/redmine
      shell: dpkg-statoverride --update --force --add redmine redmine 0750 /var/log/redmine
      shell: chown -R redmine.redmine /var/log/redmine
      shell: dpkg-statoverride --update --force --add redmine redmine 0755 /var/lib/redmine/default
      shell: dpkg-statoverride --update --force --add redmine redmine 0755 /var/lib/redmine/default/files
      shell: chown -R redmine.redmine /var/lib/redmine

    - name: Change permissions on Redmine configuration files.
      shell: dpkg-statoverride --update --force --add redmine redmine 0640 /etc/redmine/default/session.yml
      shell: dpkg-statoverride --update --force --add redmine redmine 0640 /etc/redmine/default/database.yml

    - name: Install the gitolite package (assuming that redmine and git are on the same server).
      apt: pkg=gitolite state=installed

    - name: Checkout plugins for redmine/git integration (redmine_bootstrap_kit, redmine_git_hosting).
      # mkdir /usr/share/redmine/plugins ?

      shell: git clone https://github.com/jbox-web/redmine_bootstrap_kit.git
      args:
        chdir: /usr/share/redmine/plugins
        creates: redmine_bootstrap_kit

      shell: git clone -b v0.7.9 https://github.com/jbox-web/redmine_git_hosting.git
      args:
        chdir: /usr/share/redmine/plugins
        creates: redmine_git_hosting

    - name: Deploy the Redmine configuration for smtp notifications.
      template:
        src: "templates/etc-redmine-default-configuration.yml"
        dest: "/etc/redmine/default/configuration.yml"
        owner: "redmine"
        group: "redmine"
        mode: 0644

    - name: Restart Redmine.
      service: name=redmine state=restarted
