---

# Assumes Apache

- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - acl
    - zip
    - apache2
    - libapache2-mod-php
  tags:
    - packages

# Nodejs
- name: Get the nodejs repo key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
  tags:
    - nodejs
    - packages

- apt_repository:
    repo='deb https://deb.nodesource.com/node_10.x stretch main'
    state=present
    update_cache=yes
  tags:
    - nodejs
    - packages

- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - nodejs
  tags:
    - nodejs
    - packages

# - name: Create the buildkit unix user.
#   user: name=buildkit comment="BuildKit"
# 
- name: Sudoers | create buildkit sudoers file
  template: src=etc/sudoers.d/buildkit.j2 dest=/etc/sudoers.d/buildkit owner=root group=root mode=0440
 
- name: Apache | deploy buildkit configuration
  template: src=etc/apache2/conf-available/buildkit.conf dest=/etc/apache2/conf-available/buildkit.conf owner=root group=root mode=0444

- name: Apache | enable buildkit configuration
  shell: a2enconf buildkit
  args:
    creates: /etc/apache2/conf-enabled/buildkit.conf

- name: packages | Install buildkit from git.
  git: repo=https://github.com/civicrm/civicrm-buildkit.git
       dest=/home/gitlab-runner/buildkit
  tags:
    - packages

# CiviCRM tools
- name: civicrm | Download civix, cv, civistrings and git-scan
  get_url:
    url="https://download.civicrm.org/{{ item }}/{{ item }}.phar"
    dest="/usr/local/bin/{{ item }}"
  with_items:
    - civix
    - cv
    - civistrings
    - git-scan
  tags:
    - packages

- name: civicrm | Ensure that civicrm tools (civix, cv, etc) are executable
  file: path="/usr/local/bin/{{ item }}" mode=0755
  with_items:
    - civix
    - cv
    - civistrings
    - git-scan
  tags:
    - packages
