---
# Only install basic things which must be everywhere.
- apt: update_cache=yes
  tags:
    - packages
    - common-all

- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - apt-transport-https
    - ca-certificates
    - etckeeper
    - fail2ban
    - gawk
    - git
    - libpam-yubico
    - ncdu
    - ntpdate
    - tmux
    - unzip
    - vim
    - vnstat
    - wget
  tags:
    - packages
    - common-all
