---
# Only install basic things which must be everywhere.
- apt: update_cache=yes
  tags:
    - packages

- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - etckeeper
    - fail2ban
    - git
    - libpam-yubico
    - ncdu
    - ntpdate
    - tmux
    - unzip
    - vim
    - vnstat
  tags:
    - packages
