---
# Only install basic things which must be everywhere.
- apt: update_cache=yes
  tags:
    - packages
    - common-all

- name: Configure jessie-backports
  apt_repository: repo='deb http://ftp.ca.debian.org/debian jessie-backports main contrib' state=present
  tags:
    - packages
    - packages-backports

- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - apt-transport-https
    - ca-certificates
    - etckeeper
    - fail2ban
    - gawk
    - git
    - libpam-yubico
    - ncdu
    - ntpdate
    - tmux
    - unzip
    - vim
    - vnstat
    - wget
  tags:
    - packages
    - common-all

- name: rsyslog | Deploy conf file to avoid annoying warnings
  template: src=etc/rsyslog.conf dest=/etc/rsyslog.conf owner=root group=root mode=0644
  notify: restart rsyslog
  tags:
    - common-all
    - common-all-rsyslog
