---

# We deploy our sources.list to include "contrib"
- name: common-all | Deploy apt sources.list
  template: src=etc/apt/sources.list dest=/etc/apt/sources.list owner=root group=root mode=0644
  tags:
    - common-all

- apt: update_cache=yes
  tags:
    - packages
    - common-all

- name: Configure jessie-backports
  apt_repository: repo='deb http://ftp.ca.debian.org/debian jessie-backports main contrib' state=present
  tags:
    - packages
    - packages-backports
  when: ansible_distribution_release == "jessie"

- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - etckeeper
    - fail2ban
    - gawk
    - git
    - libpam-yubico
    - ncdu
    - tmux
    - unzip
    - vim
    - vnstat
    - wget
  tags:
    - packages
    - common-all

# KVM servers run openntpd; usually not recommended to install both.
- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - ntpdate
  when: "'kvm-servers' not in group_names"
  tags:
    - packages
    - common-all

- name: rsyslog | Deploy conf file to avoid annoying warnings
  template: src=etc/rsyslog.conf dest=/etc/rsyslog.conf owner=root group=root mode=0644
  notify: restart rsyslog
  tags:
    - common-all
    - common-all-rsyslog

- name: common | Deploy keyboard default conf
  template: src=etc/default/keyboard dest=/etc/default/keyboard owner=root group=root mode=0644
  tags:
    - common-all

- name: network | Deploy IPv4 configuration
  template: src=etc/network/interfaces dest=/etc/network/interfaces owner=root group=root mode=0644
  when: preseed_ipv4_address is defined
  tags:
    - common-all
    - common-all-ipv4

- name: network | Deploy IPv6 configuration script
  template: src=etc/network/if-up.d/symbiotic-ipv6 dest=/etc/network/if-up.d/symbiotic-ipv6 owner=root group=root mode=0755
  when: preseed_ipv6_address is defined
  tags:
    - common-all
    - common-all-ipv6
