- name: MySQL | Deploy our MySQL configuration overrides
  template:
    src=etc/mysql/conf.d/symbiotic.cnf
    dest=/etc/mysql/conf.d/symbiotic.cnf
    owner=root group=root mode=0644
  notify: restart mysql

- name: MySQL | Deploy our MySQL configuration overrides for replication
  template:
    src=etc/mysql/mariadb.conf.d/60-replication.cnf
    dest=/etc/mysql/mariadb.conf.d/60-replication.cnf
    owner=root group=root mode=0644
  when: "'sql_primary_servers' in group_names or 'sql_replication_servers' in group_names"
  notify: restart mysql

- name: MySQL | Create the overrides directory
  file: path="/etc/systemd/system/mariadb.service.d" state=directory mode=0755 owner=root group=root
  tags:
    - mariadb-settings-systemd

- name: MySQL | Deploy our MySQL systemd overrides
  template:
    src=etc/systemd/system/mariadb.service.d/symbiotic.conf
    dest=/etc/systemd/system/mariadb.service.d/symbiotic.conf
    owner=root group=root mode=0644
  notify: reload systemd
  tags:
    - mariadb-settings-systemd
