- name: MySQL | Deploy our MySQL configuration overrides
  template:
    src=etc/mysql/conf.d/symbiotic.cnf
    dest=/etc/mysql/conf.d/symbiotic.cnf
    owner=root group=root mode=0644
  notify: restart mysql
  tags:
    - aegir-mysql
    - aegir-mariadb

- name: MySQL | Deploy our MySQL systemd overrides
  template:
    src=etc/systemd/system/mariadb.service.d/symbiotic.conf
    dest=/etc/systemd/system/mariadb.service.d/symbiotic.conf
    owner=root group=root mode=0644
  notify: reload systemd
  tags:
    - aegir-mysql
    - aegir-mariadb
