---

# Firewall (iptables)
- name: Install ufw
  apt: name=ufw

- name: Allow ssh
  ufw: proto=tcp port=22 rule=allow

- name: Allow http
  ufw: proto=tcp port=80 rule=allow

- name: Allow https
  ufw: proto=tcp port=443 rule=allow

- name: Allow Munin
  ufw: proto=tcp port=4949 rule=allow

- name: Set ufw policy
  ufw: state=enabled direction=incoming policy=deny

- name: Restart ufw
  service: name=ufw state=restarted
