# {{ ansible_managed }}
#
# https://grafana.com/docs/loki/latest/clients/promtail/configuration/

server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: warn

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
- url: {{ promtail_push_url }}

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      host: {{ inventory_hostname }}
      __path__: /var/log/{auth,daemon,dpkg,fail2ban,kern,mail,sys,ufw,user}*log
  pipeline_stages:
  - match:
      selector: '{job="varlogs"} |~ ".*sshd.*Received disconnect from .* Bye Bye .preauth.*"'
      action: drop
      drop_counter_reason: promtail_noisy_error
  - match:
      selector: '{job="varlogs"} |~ ".*sshd.*Disconnected from .*preauth.*"'
      action: drop
      drop_counter_reason: promtail_noisy_error
  - match:
      selector: '{job="varlogs"} |~ ".* promtail\\[.*"'
      action: drop
      drop_counter_reason: promtail_noisy_error
- job_name: nginx
  static_configs:
  - targets:
      - localhost
    labels:
      job: nginx
      host: {{ inventory_hostname }}
      __path__: /var/log/nginx/*log
  pipeline_stages:
  - match:
      selector: '{job="nginx"}'
      stages:
      - regex:
          # Example: "127.0.0.1" vhost1.example.org [01/Jan/2021:00:00:01 +0000] "GET /civicrm HTTP/1.1" 200 <body_bytes_sent> <request_length> <bytes_sent> "http://example.com/lekkebot.html" "curl/7.58.0"
          # c.f. /var/aegir/config/server_master/nginx.conf
          # The body_bytes_sent excludes the headers
          expression: '^"(?P<remote_ip>[\w\.]+)" (?P<vhost>[\w\.]+) \[(?P<timestamp>.*)\] "(?P<method>[^ ]*) (?P<request_url>[^ ]*) (?P<request_http_protocol>[^ ]*)" (?P<status>[\d]+) (?P<body_bytes_sent>[\d]+) (?P<request_length>[\d]+) (?P<bytes_sent>[\d]+) "(?P<http_referer>[^"]*)" "(?P<user_agent>[^"]*)"?'
      - labels:
          remote_ip:
          vhost:
          method:
          status:
