# Stretch does not have npm
- name: Get the nodejs repo key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
  tags:
    - nodejs
    - packages

- apt_repository:
    repo='deb https://deb.nodesource.com/node_6.x stretch main'
    state=present
    update_cache=yes
  when: ansible_distribution_release == "stretch"
  tags:
    - nodejs
    - packages

- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - nodejs
  when: ansible_distribution_release == "stretch"
  tags:
    - nodejs
    - packages
