- name: MySQL | Deploy our MySQL configuration overrides
  template:
    src=etc/mysql/conf.d/symbiotic.cnf
    dest=/etc/mysql/conf.d/symbiotic.cnf
    owner=root group=root mode=0644
  notify: restart mysql
  tags:
    - aegir-mysql
    - aegir-mariadb

# Apparently this is enabled by default in MariaDB 10.0, but not 10.1.
- name: MySQL | Enable the ARCHIVE engine
  shell: "echo 'INSTALL PLUGIN archive SONAME \'ha_archive.so\'' | mysql --defaults-file=/etc/mysql/debian.cnf"
  tags:
    - aegir-mysql
    - aegir-mariadb
