---

# Maybe this .txt file is not necessary anymore now that we use the Debian package
# although we should complete the switch and add it as an apt source:
# https://grafana.com/docs/grafana/latest/setup-grafana/installation/debian/
- name: Check if loki needs to be installed or upgraded
  stat: path="/usr/local/bin/.loki-{{ loki_version }}.txt"
  register: p
  tags:
    - packages
    - packages-loki
    - loki

- name: Install the loki Debian package
  apt:
    deb: "https://github.com/grafana/loki/releases/download/v{{ loki_version }}/loki_{{ loki_version }}_amd64.deb"
    state: present
  when: p.stat.exists == False
  tags:
    - packages
    - packages-loki
    - loki

- name: Touch the loki file
  shell: "touch /usr/local/bin/.loki-{{ loki_version }}.txt"
  when: p.stat.exists == False
  tags:
    - packages
    - packages-loki
    - loki

- name: Loki file permissions
  file: path="/usr/local/bin/loki" owner=root group=root mode=0755
  tags:
    - packages
    - packages-loki
    - loki

- name: Open the loki port for our machines only
  ufw: proto=tcp port=3100 rule=allow src="{{ item }}" route="yes"
  with_items: "{{ loki_server_allow_ips }}"
  tags:
    - loki
    - loki-ufw
    - ufw

# Not required now that we use the Debian package?
# - name: Loki lib directory permissions
#   file: path="/var/lib/loki" state=directory owner=root group=root mode=0700
#   tags:
#     - loki

- name: Loki configuration file
  template: src=etc/loki/config.yaml dest=/etc/loki/config.yaml owner=root group=root mode=0644
  notify: restart loki
  tags:
    - loki

- name: Enable the loki service
  systemd:
    name: loki
    enabled: yes
    masked: no
  tags:
    - loki
