- hosts: all
  sudo: yes

  tasks:
    - apt_key:
        url=https://packages.elasticsearch.org/GPG-KEY-elasticsearch
        state=present

    - apt_repository:
        repo='deb http://packages.elasticsearch.org/logstashforwarder/debian stable main'
        state=present
        update_cache=yes

    - apt: pkg=logstash-forwarder state=installed
