---

# Provides helpers for CiviCRM sites.
# Eventually it might replace Aegir.

- include: wordpress.yml
  when: cms == "wordpress"
  tags:
    - civicrm-sites-wordpress
    - civicrm-sites-cron-wpcivicrm

- include: drupal.yml
  when: cms == "drupal"
  tags:
    - civicrm-sites-drupal
    - civicrm-sites-cron-drupal

- include: cron-extra.yml
  tags:
    - civicrm-sites-cron-extra

- include: sftp.yml
  when: civicrm_ansible_sftpchroot_keys is defined and civicrm_ansible_sftpchroot_keys
  tags:
    - civicrm-sites-sftp

- include: monitoring.yml
  tags:
    - civicrm-sites-monitoring
