---

# Provides helpers for CiviCRM sites.
# Eventually it might replace Aegir.

- include: cron-wpcivicrm.yml
  when: cms == "wordpress"
  tags:
    - civicrm-sites-cron-wpcivicrm

- include: cron-extra.yml
  tags:
    - civicrm-sites-cron-extra
