---

# Provides helpers for CiviCRM sites.
# Eventually it might replace Aegir.

# For now, install and verify are the same (setup crons, etc)
- name: Include tasks for verify.yml
  import_tasks: verify.yml
  tags:
    - never
    - civicrm-sites-install
    - civicrm-sites-verify

# same with disable and delete (remove crons)
- name: Include tasks for delete.yml
  import_tasks: delete.yml
  tags:
    - never
    - civicrm-sites-disable
    - civicrm-sites-delete

- import_tasks: monitoring.yml
  tags:
    - civicrm-sites-monitoring
