---

- name: Clone Drush from GitHub
  git:
    repo: "{{ aegir_drush_source_repo }}"
    dest: "{{ aegir_drush_source_install_path }}"
    version: "{{ aegir_drush_source_install_version }}"
    update: "{{ aegir_drush_source_update }}"
    force: "{{ aegir_drush_source_force_update }}"
    depth: "{{ aegir_drush_source_clone_depth }}"
  register: drush_clone_result
  become: yes

# nb: we always run this, because it often happens that we re-run part of a broken install
# and otherwise we tend to use tags to do partial ansible runs
- name: Run Drush updates
  block:
  - name: Install Drush dependencies with Composer.
    command: "composer install --prefer-dist --no-interaction"
    args:
      chdir: "{{ aegir_drush_source_install_path }}"
    become: yes
  - name: Create drush symlink.
    file:
      src: "{{ aegir_drush_source_install_path }}/drush"
      dest: "{{ aegir_drush_source_install_bin_path }}"
      state: link
      force: true
    become: yes
  - name: Clear Drush cache
    shell: drush @none cc drush
    become: yes
    become_user: "{{ aegir_user }}"
  - name: Run drush to finish setting it up.
    command: "{{ aegir_drush_source_install_bin_path }}"
    register: drush_result
    changed_when: "'Execute a drush command' not in drush_result.stdout"
    become: false
