---
- name: Build Hostmaster platform.
  shell: "drush make {{ aegir_makefile_path }} {{ aegir_root }}/hostmaster --working-copy --no-gitinfofile"
  args:
    creates: "{{ aegir_root }}/hostmaster/"
  become: yes
  become_user: "{{ aegir_user }}"

- name: Use latest git for the hosting module
  shell: "cd /var/aegir/hostmaster/profiles/hostmaster/modules/aegir/hosting && git checkout symbiotic"
  become: yes
  become_user: "{{ aegir_user }}"
