---

- name: Truncate hosting_task_log before the upgrade to speed things up
  shell: "drush @hostmaster sqlq 'truncate hosting_task_log'"
  become: yes
  become_user: "{{ aegir_user }}"
  tags:
    - aegir-upgrade-hostmaster

- name: Force a drush cache flush because it can easily fail
  shell: "rm -fr /var/aegir/.drush/cache"
  become: yes
  become_user: "{{ aegir_user }}"
  tags:
    - aegir-upgrade-hostmaster

- name: Upgrade Aegir front-end.
  shell: "drush @hostmaster --yes hostmaster-migrate {{ aegir_frontend_url }} {{ aegir_root }}/hostmaster/ --working-copy"
  args:
    creates: "{{ aegir_root }}/hostmaster/sites/{{ aegir_frontend_url }}/"
  become: yes
  become_user: "{{ aegir_user }}"
  register: aegir_upgrade_task_result
  tags:
    - aegir-upgrade-hostmaster
