- hosts: all
  sudo: yes

  tasks:
    - apt_key:
        url=https://packages.elasticsearch.org/GPG-KEY-elasticsearch
        state=present

    - apt_repository:
        repo='deb http://packages.elastic.co/elasticsearch/1.7/debian stable main'
        state=present
        update_cache=yes

    - apt_repository:
        repo='deb http://packages.elasticsearch.org/logstash/1.5/debian stable main'
        state=present
        update_cache=yes

    - apt: pkg=logstash state=installed

    - apt: pkg=openjdk-8-jre state=installed

    - apt: pkg=elasticsearch state=installed

    - name: Restart Elastic Search.
      service: name=elasticsearch state=restarted

    - name: Restart Logstash.
      service: name=logstash state=restarted
