# {{ ansible_managed }}
filebeat.inputs:

# Each - is an input. Most options can be set at the input level, so
# you can use different inputs for various configurations.
# Below are the input specific configurations.

- type: log
  enabled: true
  paths:
    - /var/log/auth.log
    - /var/log/daemon.log
    - /var/log/apache2/error.log
    - /var/log/nginx/error.log
  ignore_older: 1h
  exclude_lines: [
    # CiviCRM security checks
    'AH01797: client denied by server configuration: .*delete-this',
    # These are usually bots hitting the Yubiauth
    'sshd.[0-9]+.: Connection closed by .* .preauth',
    # Cron-related messages
    'pam_unix.sudo:session.: session opened for user aegir by \\(uid=0\\)',
    'pam_unix.sudo:session.: session closed for user (root|aegir)',
    'CRON.[0-9]+.: pam_unix.cron:session.: session (opened|closed) for user [a-z0-9]+',
    # Ansible
    'sudo:[[:space:]]+deploy[[:space:]]*TTY=pts/0[[:space:]]*;[[:space:]]* PWD=/home/deploy.*ansible-tmp',
    # Other boring system stuff
    'systemd',
    'monkeysphere',
    'icinga2.* information/',
    'COMMAND=/opt/zimbra/libexec/zmmailboxdmgr status',
    # nginx: bots who can't do SSL properly
    'routines:tls_process_client_hello:unsupported protocol',
    'routines:tls_process_client_hello:version too low'
  ]

# Name of the registry file. Per default it is put in the current working
# directory. In case the working directory is changed after when running
# filebeat again, indexing starts from the beginning again.
registry_file: /var/lib/filebeat/registry

logging.level: warning

output:
  logstash:
    hosts: ["{{ filebeat_logstash_server }}:{{ filebeat_logstash_port }}"]
    ssl.enabled: true
