---

- name: Get Debmon Apt Key
  apt_key: url="http://debmon.org/debmon/repo.key" state=present

- name: Get Debmon Apt Repo
  apt_repository: repo="deb http://debmon.org/debmon debmon-{{ ansible_distribution_release }} main"
                  update_cache=yes 
                  state=present

- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - icinga2
    - monitoring-plugins-basic
  tags:
    - packages

- replace: dest=/etc/icinga2/constants.conf regexp='const TicketSalt = ""' replace='const TicketSalt = "{{ icinga2_ticket_salt }}"'

# TODO: the above stores the pass in /tmp/icinga2-salt of the host (where ansible is run from). Delete afterwards? Save?

- file: path=/etc/icinga2/pki state=directory owner=root group=nagios mode=0770

- shell: icinga2 pki new-cert --cn {{ inventory_hostname }} --key /etc/icinga2/pki/{{ inventory_hostname }}.key --cert /etc/icinga2/pki/{{ inventory_hostname }}.crt
  args:
    creates: /etc/icinga2/pki/{{ inventory_hostname }}.key

- shell: icinga2 pki save-cert --key /etc/icinga2/pki/{{ inventory_hostname }}.key --cert /etc/icinga2/pki/{{ inventory_hostname }}.crt --trustedcert /etc/icinga2/pki/trusted-master.crt --host {{ icinga2_main_node }}
  args:
    creates: /etc/icinga2/pki/trusted-master.crt

- shell: icinga2 pki ticket --cn {{ inventory_hostname }}
  delegate_to: "{{ icinga2_main_node }}"
  register: ticket

- shell: icinga2 pki request --host {{ icinga2_main_node }} --ticket {{ ticket.stdout }} --key /etc/icinga2/pki/{{ inventory_hostname }}.key --cert /etc/icinga2/pki/{{ inventory_hostname }}.crt --trustedcert /etc/icinga2/pki/trusted-master.crt --ca /etc/icinga2/pki/ca.crt
  args:
    creates: /etc/icinga2/pki/ca.crt

- name: Enable the Icinga2 API
  shell: icinga2 feature enable api 
  args:
    creates: /etc/icinga2/features-enabled/api.conf
  notify: restart icinga
