---

- name: Force gathering facts for partial ansible runs
  setup:
  tags:
    - packages
    - icinga2

- name: Get Icinga Apt Key for IPv6
  apt_key:
    url="https://packages6.icinga.com/icinga.key"
    state=present
  when: preseed_ipv4_address is not defined
  tags:
    - packages
    - icinga2

- name: Get Icinga Apt Key
  apt_key:
    url="https://packages.icinga.com/icinga.key"
    state=present
  when: preseed_ipv4_address is defined
  tags:
    - packages
    - icinga2

- name: Configure Icinga Apt IPv6-only Repo
  apt_repository:
    repo="deb https://packages6.icinga.com/{{ ansible_distribution|lower }} icinga-{{ ansible_distribution_release }} main"
    update_cache=yes
    state=present
  when: preseed_ipv4_address is not defined
  tags:
    - packages
    - icinga2

- name: Configure Icinga Apt Repo
  apt_repository:
    repo="deb https://packages.icinga.com/{{ ansible_distribution|lower }} icinga-{{ ansible_distribution_release }} main"
    update_cache=yes
    state=present
  when: preseed_ipv4_address is defined
  tags:
    - packages
    - icinga2

- include: main-server.yml
  when: "'icinga_servers' in group_names"
  tags:
    - icinga2

- include: main-node.yml
  when: "'icinga_servers' not in group_names"
  tags:
    - icinga2

- include: main-conf-host.yml
  when: "'icinga_servers' not in group_names"
  tags:
    - never
    - icinga2-conf-host

- include: main-conf-host-local.yml
  when: "'icinga_servers' not in group_names"
  tags:
    - never
    - icinga2-conf-host-local
