---

- name: Get Icinga Apt Key
  apt_key:
    url="https://packages.icinga.com/icinga.key"
    state=present
  tags:
    - icinga2
    - packages
  when: ansible_distribution == "Debian"

- name: Configure Icinga Apt Repo
  apt_repository:
    repo="deb http://packages.icinga.com/debian icinga-{{ ansible_distribution_release }} main"
    update_cache=yes 
    state=present
  tags:
    - icinga2
    - packages

- include: main-server.yml
  when: "'icinga-servers' in group_names"

- include: main-node.yml
  when: "'icinga-servers' not in group_names"
