---

- apt: pkg=apt-transport-https state=installed
  tags:
    - docker
    - packages

- name: Get the Docker repo key
  apt_key: url=https://apt.dockerproject.org/gpg state=present
  tags:
    - docker
    - packages

- apt_repository:
    repo='deb https://apt.dockerproject.org/repo debian-{{ ansible_distribution_release }} main'
    state=present
    update_cache=yes
  tags:
    - docker
    - packages

- apt: pkg=docker-engine state=installed
  tags:
    - docker
    - packages
