---
# Assumes Debian/Ubuntu, with MariaDB, Nginx, php-7.x-fpm
#
# @todo Duplicates a lot of things from the 'aegir' role
# and no longer a reason to duplicate

- name: Force gathering facts for partial ansible runs
  setup:
  tags:
    - packages
    - packages-php
    - php-php
    - php-settings

- name: Debian | Add Sury.org apt reporitory key
  apt_key:
    url: "https://packages.sury.org/php/apt.gpg"
    state: present
    keyring: /etc/apt/trusted.gpg.d/php.gpg
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  tags:
    - packages
    - packages-php
    - php-php

- name: Debian | Add Sury.org repository
  apt_repository:
    repo: deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main
    state: present
    update_cache: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  tags:
    - packages
    - packages-php
    - php-php

- name: Debian | Pin Sury repositories
  template: src=etc/apt/preferences.d/php-symbiotic dest=/etc/apt/preferences.d/php-symbiotic owner=root group=root mode=0444
  tags:
    - packages
    - packages-php
    - php-php

- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - curl
    - gettext
  tags:
    - packages
    - packages-php
    - php-php

- apt:
    name: [
      "php{{ phpversion }}",
      "php{{ phpversion }}-bcmath",
      "php{{ phpversion }}-gd",
      "php{{ phpversion }}-cli",
      "php{{ phpversion }}-curl",
      "php{{ phpversion }}-intl",
      "php{{ phpversion }}-json",
      "php{{ phpversion }}-ldap",
      "php{{ phpversion }}-mysql",
      "php{{ phpversion }}-soap",
      "php{{ phpversion }}-ssh2",
      "php{{ phpversion }}-zip",
      "php{{ phpversion }}-xsl",
      "php{{ phpversion }}-mbstring",
      "php{{ phpversion }}-zip",
      "php{{ phpversion }}-imagick"
    ]
    state: present
    install_recommends: no
  when: phpversion != 8.0
  tags:
    - packages
    - packages-php
    - php-php

# PHP 8.0 does not have php8.0-json
- apt:
    name: [
      "php{{ phpversion }}",
      "php{{ phpversion }}-bcmath",
      "php{{ phpversion }}-gd",
      "php{{ phpversion }}-cli",
      "php{{ phpversion }}-curl",
      "php{{ phpversion }}-intl",
      "php{{ phpversion }}-ldap",
      "php{{ phpversion }}-mysql",
      "php{{ phpversion }}-soap",
      "php{{ phpversion }}-ssh2",
      "php{{ phpversion }}-zip",
      "php{{ phpversion }}-xsl",
      "php{{ phpversion }}-mbstring",
      "php{{ phpversion }}-zip",
      "php{{ phpversion }}-imagick"
    ]
    state: present
    install_recommends: no
  when: phpversion == 8.0
  tags:
    - packages
    - packages-php
    - php-php

# A bit off topic, but too often had the issue where mailname was misconfigured
# @todo Is it relevant in this role? maybe common-all? (probably old copy-paste)
- copy: content="{{ inventory_hostname }}" dest=/etc/mailname
- file: path=/etc/mailname owner=root group=root mode=0644

- include: settings-php.yml
  tags:
    - php-php
    - php-settings
