- name: Deploy our PHP ini overrides.
  template:
    src=etc/php/{{ phpversion }}/mods-available/90-symbiotic.ini
    dest=/etc/php/{{ phpversion }}/mods-available/90-symbiotic.ini
    owner=root group=root mode=0644
  notify: "restart php{{ phpversion }}-fpm"

- name: Symlink PHP ini settings for php-fpm
  file: src="/etc/php/{{ phpversion }}/mods-available/90-symbiotic.ini" dest="/etc/php/{{ phpversion }}/fpm/conf.d/90-symbiotic.ini"
        owner=root group=root state=link
  notify: "restart php{{ phpversion }}-fpm"
