---
- name: restart php7.4-fpm
  service: name=php7.4-fpm state=restarted

- name: restart php8.0-fpm
  service: name=php8.0-fpm state=restarted

- name: restart php8.1-fpm
  service: name=php8.1-fpm state=restarted
